### PR TITLE
Arbitrum Bridge Fix

### LINKED ISSUE #1699: CRITICAL - Unable to collect after bridging for ERC20
Hey, we fixed some bridging issues earlier in this PR #1628 but seems like this only fixed part of the problem. When a user is trying to collect DXD, he is not able to collect it. Maybe we left some issues behind :)

https://www.loom.com/share/6c209713e742452a93efa6c86e828cde

Testing considerations:
Test these combinations from Goerli to Arb Goerli 
- ETH
- WETH
- any other ERC20, prefer if we can have DXD in Goerli and Arb Goerli

### PR DESCRIPTION
**Pull request by bejzik8**
# Summary

This pull request updates `Arbitrum Bridge` by fixing `collect` method. Users should be able to collect their tokens now.

Tested multiple times, video here: https://www.loom.com/share/f07fa3e8341f492b84fc9f74bcc88815. 

Resolves #1699.

🍀

### CODE REVIEW

**Comment by wixzi** [comment]
@bejzik8  Can you add a task to update to stable arbitrum/skd v3.0.0. Now we are using the beta version.

**Review by wixzi — APPROVED** [review]
Looks good. But why now batchIndex and batchNumber not working?

**Comment by bejzik8** [comment]
> arbitrum/skd

Sure, I can. 👍🏼

**Comment by bejzik8** [comment]
Created task to update `@arbitrum/sdk` - https://github.com/ImpeccableHQ/swapr-dapp/issues/1711.

**Comment by 0xVenky** [comment]
Not sure why Netlify is failing - https://deploy-preview-1707--swapr.netlify.app/#/swap/pro?chainId=1 use this direct URL instead.

**Comment by MilanVojnovic95** [comment]
@bejzik8  Retested and still fails 😞

**Comment by bejzik8** [comment]
@MilanVojnovic95, what is happening with this?

Check this out: https://www.loom.com/share/2cab482b4eb842e091e886cbdb041211.

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍 

It is possible to make transactions on Goerli and Arbitrum Goerli network, also some transactions show the "Collect" option and some are in "Pending" state even though the bridge is executed, I think this should be further investigated when it is merged to develop, but for now it is good enough for merge.

@0xVenky Your opinion?

**Comment by 0xVenky** [comment]
> Tested and looks ok to me 👍 
> 
> It is possible to make transactions on Goerli and Arbitrum Goerli network, also some transactions show the "Collect" option and some are in "Pending" state even though the bridge is executed, I think this should be further investigated when it is merged to develop, but for now it is good enough for merge.
> 
> @0xVenky Your opinion?

Sounds good. Lets also try to test in Arb1 to mainnet after this is merged. But good to merge n release :)

**Pull request merged**
