### PR TITLE
1Inch Eco Router

### PR DESCRIPTION
**Pull request by Mi-Lan**
This pull request (PR) includes an implementation that adds support for the 1inch aggregation protocol to the swapr-sdk eco router. This is a two-part implementation, with the second part being found in the PR here on the sdk repo: https://github.com/ImpeccableHQ/swapr-sdk/pull/254.

To test the implementation, follow these steps 👍 

1) Go to the swapbox.
2) Input an amount of currency from the list of supported tokens found in the 1inch documentation: https://docs.1inch.io/docs/aggregation-protocol/api/swagger.
3) You should see 1inch as an option in the ecoRouter.
Note: This implementation supports the following chains: MAINNET, ARBITRUM_ONE, POLYGON, OPTIMISM_MAINNET, GNOSIS, BSC_MAINNET.

Here is a screenshot of how it should look 

Screenshot 2023-01-24 at 18 23 54

### CODE REVIEW

**Review by berteotti — COMMENTED** [review]
Code looks good, will approve when sdk version is fixed :)

**Comment by MilanVojnovic95** [comment]
Tested.
Wherever I try to do the swap I get this message, also 1inch is missing in the animation when the swap button is in loading mode.

image

**Comment by Mi-Lan** [comment]
> Tested. Wherever I try to do the swap I get this message, also 1inch is missing in the animation when the swap button is in loading mode.
> 
> image

Can you give steps to reproduce?

**Comment by Mi-Lan** [comment]
@MilanVojnovic95 Could you test it again it should work now

**Review by MilanVojnovic95 — APPROVED** [review]
Retested and looks ok to me 👍

**Pull request merged**
